// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh5waM9PGJUqv__Swyqxx-0AFHTsxNAAk',
    appId: '1:716960100006:web:b21b9cb3c07834c414ce67',
    messagingSenderId: '716960100006',
    projectId: 'fir-project-1-34187',
    authDomain: 'fir-project-1-34187.firebaseapp.com',
    storageBucket: 'fir-project-1-34187.firebasestorage.app',
    measurementId: 'G-89TBKS0HN8',
    databaseURL: 'https://fir-project-1-34187-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYD9YDTbr0Di6C_YRmK8a8s4uRShwfiJM',
    appId: '1:716960100006:android:0709b1431f3977cc14ce67',
    messagingSenderId: '716960100006',
    projectId: 'fir-project-1-34187',
    storageBucket: 'fir-project-1-34187.firebasestorage.app',
    databaseURL: 'https://fir-project-1-34187-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZOU85zORG9pzPstSfpMd9F-vvKoC13c',
    appId: '1:716960100006:ios:a4106ae524c39fa114ce67',
    messagingSenderId: '716960100006',
    projectId: 'fir-project-1-34187',
    storageBucket: 'fir-project-1-34187.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
    databaseURL: 'https://fir-project-1-34187-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZOU85zORG9pzPstSfpMd9F-vvKoC13c',
    appId: '1:716960100006:ios:a4106ae524c39fa114ce67',
    messagingSenderId: '716960100006',
    projectId: 'fir-project-1-34187',
    storageBucket: 'fir-project-1-34187.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
    databaseURL: 'https://fir-project-1-34187-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh5waM9PGJUqv__Swyqxx-0AFHTsxNAAk',
    appId: '1:716960100006:web:8c347750fcc9b39614ce67',
    messagingSenderId: '716960100006',
    projectId: 'fir-project-1-34187',
    authDomain: 'fir-project-1-34187.firebaseapp.com',
    storageBucket: 'fir-project-1-34187.firebasestorage.app',
    measurementId: 'G-F3QBEQ979E',
    databaseURL: 'https://fir-project-1-34187-default-rtdb.firebaseio.com/',
  );
}
